homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 57
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include_dir_merge_named customize

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor weather:
  platform: yr

logger:
  default: info

rfxtrx:
  device: /dev/rfxtrx
  debug: True
  dummy: False

sensor rfxtrx:
  platform: rfxtrx
  automatic_add: True
  devices:
    085001000401005069:
      name: outdoor_temperature
      data_type:
        - Temperature
    0a520906690000df2c0179:
      name: th01
      data_type:
        - Temperature
        - Humidity
    0a520904870000a12d0159:
      name: th02
      data_type:
        - Temperature
        - Humidity
    0a5209024b0000d32f0179:
      name: th03
      data_type:
        - Temperature
        - Humidity
    08500900001100e069:
      name: bbq
      data_type:
        - Temperature

device_tracker bluetooth:
  platform: bluetooth_tracker

zwave:
  usb_path: /dev/zstick
  config_path: /usr/local/etc/openzwave
  polling_interval: 60000

group: !include_dir_merge_named group

light:
  platform: rfxtrx
  automatic_add: True
  signal_repetitions: 1
  devices:
    0b11000d0085feb601010f70:
      name: livingroom_window
    0b11000f0085feb602010f70:
      name: livingroom_other
    0b11000f0085feb603010f70:
      name: livingroom_corner
    0b11000d0085feb605010f70:
      name: outdoor
    0b11000d0085feb606010f70:
      name: playroom
    0b11000d0085feb608010f70:
      name: attic_window
    0b11000d0085feb609010f70:
      name: basement_box_room

sensor templates:
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ "%+.1f" | format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'
      sunrise:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
      sunset:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'

automation: !include_dir_merge_list automation

binary_sensor:
  - platform: template
    sensors:
      playroom_motion:
        entity_id: sensor.playroom_burglar_3_10
        value_template: '{{ is_state("sensor.playroom_burglar_3_10", "8") }}'

switch:
  - platform: template
    switches:
      outdoor_front:
        entity_id: switch.outdoor_front_switch_4_0
        value_template: '{{ is_state("switch.outdoor_front_switch_4_0", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.outdoor_front_switch_4_0
        turn_off:
          service: switch.turn_off
          entity_id: switch.outdoor_front_switch_4_0

script: !include_dir_merge_named script
