homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 57
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  packages: !include_dir_named packages

recorder:
#  db_url: mysql://hass:nopassword@localhost/hass?charset=utf8

# Enables the frontend
frontend:

http:
  server_host: 127.0.0.1
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 3

# Enable the iOS component
ios:

# Enable mobile apps
mobile_app:

# Enable Home Assistant configuration
config:

# Discover some devices automatically
discovery:
  # ignore:
  #   - philips_hue

# Enable python scripts from directory python_scripts
python_script:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Enable ffmpeg plugin which is needed for onvif
ffmpeg:

#edgeos:
#  host: 10.10.0.1
#  #Supports SSL (true/false) - should be true
#  ssl: true
#  #Username of EdgeOS
#  username: !secret edgeos_username
#  #Password of EdgeOS
#  password: !secret edgeos_password
#  #Path to the certificate (full-chain)
#  #cert_file: !secret ssl_certificate
#  #List of interfaces
#  monitored_interfaces:
#      - eth0
#  #List of network devices to monitor
#  monitored_devices:
#      - PC1
#      - PC2
#  #Optional - Allowed values:
#  #  '' - represents bytes
#  #  'K' - represents Kilobytes
#  #  'M' - represents Megabytes
#  unit: 'M'

# Connect to my Ubiquiti Edge Router X in order to track
# connected devices.
#device_tracker:
#  - platform: edgeos

system_health:

influxdb:
  host: localhost
  database: hass
  include:
    entities:
      # outdoor
      - sensor.outdoor_temperature
      - sensor.outdoor_driveway_luminance
      - sensor.outdoor_driveway_humidity
      - sensor.outdoor_driveway_temperature
      - sensor.outdoor_driveway_battery
      # entrance
      - alarm_control_panel.herdevagen_26_b_alarm
      - sensor.main_door
      - sensor.entrance_temperature
      # livingroom
      - sensor.balcony_door
      # kitchen
      - sensor.kitchen_humidity
      - sensor.kitchen_temperature
      # bathroom
      - binary_sensor.bathroom_status
      - sensor.bathroom_luminance
      - sensor.bathroom_relative_humidity
      - sensor.bathroom_temperature
      # guestroom
      - binary_sensor.guestroom_status
      - sensor.guestroom_temperature
      # playroom
      - sensor.playroom_temperature
      # gillestugan
      - sensor.th02_humidity
      - sensor.th02_temperature
      - sensor.gillestugan_humidity
      - sensor.gillestugan_temperature
      # garage 1
      - binary_sensor.garage1_door
      # garage 2
      - binary_sensor.garage2_door
      - switch.plant_lights
      # laundry
      - sensor.laundry_door
      - sensor.laundry_humidity
      - sensor.laundry_temperature
      - switch.laundry_dehumidifier
      - sensor.laundry_dehumidifier_power
      - sensor.laundry_dehumidifier_energy
      - sensor.laundry_washing_machine_power
      - sensor.laundry_washing_machine_energy
      # butlery (matkällaren)
      - sensor.th01_humidity
      - sensor.th01_temperature
      # attic
      - sensor.attic_heating_cable_energy
      - sensor.attic_heating_cable_power
      - sensor.attic_ventilation_power
      - sensor.attic_ventilation_energy
      - sensor.attic_th03_temperature
      - sensor.attic_th03_humidity
      - sensor.attic_th04_temperature
      - sensor.attic_th04_humidity
      # appliances
      - sensor.freezer_temperature
      - sensor.refrigerator_temperature
      - sensor.freezer_in_g2_temperature
      # heatpump
      - sensor.heatpump_0001 # "Radiator Retur GT1" # "Radiator Return"
      - sensor.heatpump_0003 # "Värmebärare In GT9" # "Heat carrier Return"
      - sensor.heatpump_0004 # "Värmebärare Ut GT8" # "Heat carrier Forwrd"
      - sensor.heatpump_0005 # "Köldbärare In GT10" # "Brine in/Evaporator"
      - sensor.heatpump_0006 # "Köldbärare Ut GT11" # "Brine out/Condenser"
      - sensor.heatpump_0007 # "Utomhustemperatur" # "Outdoor"
      - sensor.heatpump_000a # "Varmvatten GT3" # "Hot water 2 / Mid"
      - sensor.heatpump_000b # "Kompressor GT6" # "Hot gas / Compr."
      - sensor.heatpump_0107 # "Börvärde Radiator Retur" # Heating setpoint"
      - sensor.heatpump_0111 # "Börvärde Varmvatten" # "Warm water setpoint"
      - sensor.heatpump_1a01 # "Kompressor" # "Compressor"
      - sensor.heatpump_1a02 # "Elkasett 1" # "Add heat step 1"
      - sensor.heatpump_1a03 # "Elkasett 2" # "Add heat step 2"
      - sensor.heatpump_1a04 # "Köldbärarpump" # "Pump Cold circuit"
      - sensor.heatpump_1a05 # "Värmebärarpump" # "Pump Heat circuit"
      - sensor.heatpump_1a06 # "Radiatorpump" # "Pump Radiator"
      - sensor.heatpump_1a07 # "Växelventil (värme/varmvatten)" # "Switch valve 1"
      # emeter_heatpump
      - sensor.emeter_heatpump_power
      # watermeter
      - sensor.watermeter_volume
      # lawnmower gardena sileno
      - vacuum.sileno
      # pool
      - binary_sensor.pool_status
      - sensor.pool_daily_energy
      - sensor.pool_power
      - switch.pool

logger:
  default: info
  logs:
    # homeassistant.components.rfxtrx: debug
    # homeassistant.components.rfxtrx.binary_sensor: debug
    # homeassistant.components.rfxtrx.cover: debug
    # homeassistant.components.rfxtrx.light: debug
    # homeassistant.components.rfxtrx.sensor: debug
    # homeassistant.components.rfxtrx.switch: debug
    # homeassistant.components.heos: debug
    # homeassistant.components.mysensors: debug
    # openzwave: debug
    pyarlo: debug

rfxtrx:
  device: /dev/rfxtrx
  automatic_add: True

# hue:
#   bridges:
#     - host: 10.10.0.41
#       allow_unreachable: false
#       allow_hue_groups: true

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

alarm_control_panel:
  - platform: arlo
    home_mode_name: Avaktiverat
    away_mode_name: Aktiverat

ifttt:
  key: !secret ifttt_key

sensor:
  - platform: arlo
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_1m
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ "%+.1f" | format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'
      sunrise:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
      sunset:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
      main_door:
        value_template: >-
          {% if is_state('lock.entredorr', 'locked') %}
            låst
          {% elif is_state('binary_sensor.entredorr', 'off') %}
            olåst
          {% else %}
            öppen
          {% endif %}
        icon_template: >-
          {% if is_state('lock.entredorr', 'locked') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
      balcony_door:
        value_template: >-
          {% if is_state('binary_sensor.altandorr', 'off') %}
            låst
          {% else %}
            öppen
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.altandorr', 'off') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
      alarm_status_ui:
        value_template: >-
          {% if is_state("alarm_control_panel.herdevagen_26_b_alarm", "armed_away") %}
            larmat i bortaläge
          {% elif is_state("alarm_control_panel.herdevagen_26_b_alarm", "armed_home") %}
            larmat i hemmaläge (skalskydd)
          {% elif is_state("alarm_control_panel.herdevagen_26_b_alarm", "disarmed") %}
            avlarmat
          {% else %}
            okänt
          {% endif %}
        icon_template: >-
          {% if is_state("alarm_control_panel.herdevagen_26_b_alarm", "armed_away") %}
            mdi:run
          {% elif is_state("alarm_control_panel.herdevagen_26_b_alarm", "disarmed") %}
            mdi:home
          {% else %}
            mdi:minus
          {% endif %}

#  - platform: mqtt
#    name: 'laundry_emeter1_energy'
#    state_topic: 'laundry/e-meter/1'
#    unit_of_measurement: 'kWh'
#    value_template: '{{ value_json.energy }}'
#  - platform: mqtt
#    name: 'laundry_emeter1_power'
#    state_topic: 'laundry/e-meter/1'
#    unit_of_measurement: 'W'
#    value_template: '{{ value_json.power }}'

camera:
#  - platform: arlo
#  - platform: uvc
#    nvr: localhost
#    port: 7080
#    key: !secret uvc_key
#  - platform: local_file
#    name: camera1_latest
#    file_path: /home/camera1/latest.jpg
#  - platform: local_file
#    name: camera2_latest
#    file_path: /home/camera2/latest.jpg
  - platform: generic
    name: weather
    # Fetch only one time per minute
    still_image_url: "https://www.yr.no/place/Sweden/Stockholm/Stockholm/meteogram.svg?dummy={{as_timestamp(now())|timestamp_custom('%Y-%m-%d_%H%M') }}"
    content_type: "image/svg+xml"
    limit_refetch_to_url_change: true
#  - platform: onvif
#    name: camera1
#    host: 10.10.0.113
#    port: 49152
#    username: view
#    password: view
#    profile: 2
#  - platform: onvif
#    name: camera2
#    host: 10.10.0.102
#    port: 49152
#    username: view
#    password: view
#    profile: 2
#  - platform: ffmpeg
#    name: camera1_live
#    input: rtsp://view:view@10.10.0.113:554/live/ch2
#  - platform: ffmpeg
#    name: camera2_live
#    input: rtsp://view:view@10.10.0.102:554/live/ch2

heos:
  host: heos_livingroom

#media_player:
#  - platform: heos
#    hostname: heos_livingroom
#    name: HEOS Sound System

panel_iframe:
  grafana:
    title: 'Grafer'
    url: 'https://grafana.jabbe.se'
    icon: mdi:chart-line

mqtt:
  broker: localhost

verisure:
  username: jakegrabben@hotmail.com
  password: !secret verisure_password
  code_digits: 6

zwave:
  usb_path: /dev/zstick
  polling_interval: 60000
  debug: False

group: !include_dir_merge_named group

#light:
#   - platform: twinkly
#     host: Twinkly_D57321
#     name: twinkly_lights

automation: !include_dir_merge_list automation

script: !include_dir_merge_named script

# Scenes are handled by a AppDaemon script listening for the
# scene.turn_on service_call.
scene:
  - name: morning
    entities:
      switch.dummy: true
  - name: day
    entities:
      switch.dummy: true
  - name: afternoon
    entities:
      switch.dummy: true
  - name: evening
    entities:
      switch.dummy: true
  - name: night
    entities:
      switch.dummy: true
