homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 57
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  customize: !include customize.yaml
  packages: !include_dir_named packages

recorder:
  db_url: mysql+pymysql://hass:nopassword@localhost/hass?charset=utf8

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password

# Checks for available updates
updater:

# Enable the iOS component
ios:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

influxdb:
  host: localhost
  database: hass
  include:
    entities:
      - alarm_control_panel.herdevagen_26_b_alarm
      - lock.entredorr
      - sensor.balcony_door
      - sensor.bathroom_status
      - sensor.aeotec_zw100_multisensor_6_temperature
      - sensor.aeotec_zw100_multisensor_6_relative_humidity
      - sensor.dehumidifier
      - sensor.entre_temperature
      - sensor.fibaro_system_fgwpef_wall_plug_gen5_energy
      - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
      - sensor.freezer_temperature
      - sensor.gillestugan_humidity
      - sensor.gillestugan_temperature
      - sensor.guestroom_status
      - sensor.kok_humidity
      - sensor.kok_temperature
      - sensor.laundry_door
      - sensor.main_door
      - sensor.swz002_energy
      - sensor.swz002_power
      - sensor.th01_humidity
      - sensor.th01_temperature
      - sensor.th02_humidity
      - sensor.th02_temperature
      - sensor.th03_humidity
      - sensor.th03_temperature
      - sensor.tvattstuga_humidity
      - sensor.tvattstuga_temperature

logger:
  default: warning
#  logs:
#    homeassistant.components.rfxtrx: debug

rfxtrx:
  device: /dev/rfxtrx
  debug: False
  dummy: False

sensor:
  - platform: yr
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: load_1m
  - platform: rfxtrx
    automatic_add: False
    devices:
      085001000401005069:
        name: outdoor
        data_type:
          - Temperature
      0a520906690000df2c0179:
        name: th01
        data_type:
          - Temperature
          - Humidity
      0a520904870000a12d0159:
        name: th02
        data_type:
          - Temperature
          - Humidity
      0a5209024b0000d32f0179:
        name: th03
        data_type:
          - Temperature
          - Humidity
      0850096500ab019269:
        name: bbq
        data_type:
          - Temperature
      08500900001100e069:
        name: bbq_old
        data_type:
          - Temperature
      0a520907970000ba1e0259:
        name: freezer
        data_type:
          - Temperature
      0a520c1a000100e6050279:
        name: soil_moisture1
        data_type:
          - Temperature
          - Humidity
      0a52090bc70000fb2c0159:
        name: soil_moisture2
        data_type:
          - Temperature
          - Humidity
      0a520c02000300dc500359:
        name: soil_moisture3
        data_type:
          - Temperature
          - Humidity
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ "%+.1f" | format(states.sun.sun.attributes.elevation) }}'
        unit_of_measurement: '°'
      sunrise:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%H:%M") }}'
      sunset:
        value_template: '{{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%H:%M") }}'
      dehumidifier:
        entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
        value_template: '{{ states.switch.fibaro_system_fgwpef_wall_plug_gen5_switch.attributes.power_consumption }}'
        unit_of_measurement: 'W'
      main_door:
        value_template: >-
          {% if is_state('lock.entredorr', 'locked') %}
            låst
          {% elif is_state('binary_sensor.entredorr', 'off') %}
            olåst
          {% else %}
            öppen
          {% endif %}
        icon_template: >-
          {% if is_state('lock.entredorr', 'locked') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
      balcony_door:
        value_template: >-
          {% if is_state('binary_sensor.altandorr', 'off') %}
            låst
          {% else %}
            öppen
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.altandorr', 'off') %}
            mdi:lock
          {% else %}
            mdi:lock-open
          {% endif %}
      bathroom_status:
        value_template: >-
          {% if is_state("sensor.aeotec_zw100_multisensor_6_burglar", "8") %}
            upptaget
          {% else %}
            ledigt
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.aeotec_zw100_multisensor_6_burglar", "8") %}
            mdi:close-circle
          {% else %}
            mdi:human-male-female
          {% endif %}
      guestroom_status:
        value_template: >-
          {% if is_state("binary_sensor.guestroom", "on") %}
            upptaget
          {% else %}
            ledigt
          {% endif %}
        icon_template: >-
          {% if is_state("binary_sensor.guestroom", "on") %}
            mdi:close-circle
          {% else %}
            mdi:human-male-female
          {% endif %}
      laundry_door:
        value_template: >-
          {% if is_state("binary_sensor.laundry", "on") %}
            öppen
          {% elif is_state("binary_sensor.laundry", "off") %}
            stängd
          {% else %}
            okänd
          {% endif %}
        icon_template: >-
          {% if is_state("binary_sensor.laundry", "on") %}
            mdi:door-open
          {% elif is_state("binary_sensor.laundry", "off") %}
            mdi:door-closed
          {% else %}
            mdi:dots-horizontal
          {% endif %}
      playroom_motion:
        value_template: >-
          {% if is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") %}
            leks för fullt
          {% else %}
            ingen aktivitet
          {% endif %}
        icon_template: >-
          {% if is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") %}
            mdi:snowman
          {% else %}
            mdi:radiobox-blank
          {% endif %}
      garage1_door:
        value_template: >-
          {% if is_state('sensor.vision_zg8101_garage_door_detector_alarm_level', '0') %}
            stängd
          {% elif is_state('sensor.vision_zg8101_garage_door_detector_alarm_level', '255') %}
            öppen
          {% else %}
            okänt
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.vision_zg8101_garage_door_detector_alarm_level', '0') %}
            mdi:door-closed
          {% elif is_state('sensor.vision_zg8101_garage_door_detector_alarm_level', '255') %}
            mdi:door-open
          {% else %}
            mdi:dots-horizontal
          {% endif %}
  - platform: mqtt
    name: 'laundry_emeter1_energy'
    state_topic: 'laundry/e-meter/1'
    unit_of_measurement: 'kWh'
    value_template: '{{ value_json.energy }}'
  - platform: mqtt
    name: 'laundry_emeter1_power'
    state_topic: 'laundry/e-meter/1'
    unit_of_measurement: 'W'
    value_template: '{{ value_json.power }}'

camera:
  - platform: local_file
    name: camera1
    file_path: /home/camera1/latest.jpg
  - platform: local_file
    name: washm
    file_path: /home/hass/hass-conf/washm-example.jpg
  - platform: generic
    name: weather
    still_image_url: "https://www.yr.no/place/Sweden/Stockholm/Stockholm/meteogram.svg"
    content_type: "image/svg+xml"

panel_iframe:
  grafana:
    title: 'Grafer'
    url: 'http://atom.home:3000'

mqtt:
  broker: localhost

verisure:
  username: jakegrabben@hotmail.com
  password: !secret verisure_password
  code_digits: 6

zwave:
  usb_path: /dev/zstick
  config_path: /home/hass/hass-conf/deps/python_openzwave/ozw_config
  polling_interval: 60000
  debug: False

group: !include_dir_merge_named group

light:
  platform: rfxtrx
  automatic_add: False
  signal_repetitions: 1
  devices:
    0b11000d0085feb601010f70:
      name: livingroom_corner
    0b11000f0085feb602010f70:
      name: livingroom_front
    0b11000d0085feb605010f70:
      name: outdoor
    0b11000d0085feb606010f70:
      name: playroom
    0b11000d0085feb607010f70:
      name: guestroom
    0b11000d0085feb608010f70:
      name: attic_window
    0b11000d0085feb609010f70:
      name: basement_box_room

automation: !include_dir_merge_list automation

binary_sensor:
  - platform: rfxtrx
    automatic_add: False
    devices:
      0b110005007abc960a010f60:
        name: guestroom
      0b11002a0023034e0a000070:
        name: laundry
  - platform: template
    sensors:
      playroom_motion:
        entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
        value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") }}'

switch:
  - platform: template
    switches:
      outdoor_front:
        entity_id: switch.everspring_an179_in_wall_onoff_module_switch
        value_template: '{{ is_state("switch.everspring_an179_in_wall_onoff_module_switch", "on") }}'
        turn_on:
          service: switch.turn_on
          entity_id: switch.everspring_an179_in_wall_onoff_module_switch
        turn_off:
          service: switch.turn_off
          entity_id: switch.everspring_an179_in_wall_onoff_module_switch

script: !include_dir_merge_named script

scene: !include_dir_merge_list scenes
