- alias: Disable attic ventilation in the evening
  trigger:
    platform: time
    at: '20:00:00'
  action:
    service: switch.turn_off
    entity_id: switch.swz002_switch

- alias: Enable attic ventilation later
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.swz002_switch
