- alias: Close cover in bedrooms at evening
  trigger:
    platform: time
    at: '19:00:00'
  action:
    service: cover.close_cover
    entity_id:
      - cover.qubino_zmnhod1_flush_shutter_dc_switch
      - cover.qubino_zmnhod1_flush_shutter_dc_switch_2
- alias: Open cover in bedrooms at morning
  trigger:
    platform: time
    at: '07:30:00'
  action:
    service: cover.open_cover
    entity_id:
      - cover.qubino_zmnhod1_flush_shutter_dc_switch
      - cover.qubino_zmnhod1_flush_shutter_dc_switch_2
