- alias: Close cover in bedrooms at evening
  trigger:
    platform: time
    at: '19:45:00'
  action:
    service: cover.close_cover
    entity_id:
      - cover.master_bedroom
      - cover.bedroom2
- alias: Open cover in bedrooms at weekdays morning
  trigger:
    platform: time
    at: '07:00:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: cover.open_cover
    entity_id:
      - cover.master_bedroom
      - cover.bedroom2
- alias: Open cover in bedrooms on Saturday and Sunday mornings
  trigger:
    platform: time
    at: '08:00:00'
  condition:
    - condition: time
      weekday:
        - sat
        - sun
  action:
    service: cover.open_cover
    entity_id:
      - cover.master_bedroom
      - cover.bedroom2
