- alias: Soften lights in guestroom on motion during night
  trigger:
    platform: state
    entity_id: binary_sensor.guestroom
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ states.sun.sun.attributes.elevation < 0 }}"
      - condition: time
        after: '21:30:00'
        before: '05:30:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.guest_toilet
      brightness_pct: 1
