- alias: Turn on lights when turning switch in hallway on
  trigger:
    platform: state
    entity_id: switch.hall
    from: 'off'
    to: 'on'
  action:
    service: scene.turn_on
    entity_id:
      - scene.afternoon

- alias: Turn off lights when pressing toggle switch in hallway
  trigger:
    platform: state
    entity_id: switch.hall
    to: 'off'
  action:
    service: scene.turn_on
    entity_id:
      - scene.night
