- alias: Turn on indoor lights in early morning
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  action:
    service: scene.turn_on
    entity_id:
      - scene.morning

- alias: Turn off indoor lights when sun is up
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 5.0
  action:
    service: scene.turn_on
    entity_id:
      - scene.day

- alias: Turn on indoor lights when sun goes down
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: time
    before: '20:15:00'
  action:
    service: scene.turn_on
    entity_id:
      - scene.afternoon

- alias: Enter evening mode at 20:15 if sun is down
  trigger:
    platform: time
    at: '20:15:00'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  action:
    service: scene.turn_on
    entity_id:
      - scene.evening

- alias: Enter evening mode when sun goes down
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 5.0
  condition:
    condition: and
    conditions:
      - condition: time
        after: '20:15:00'
      - condition: time
        before: '22:30:00'
  action:
    service: scene.turn_on
    entity_id:
      - scene.evening

- alias: Turn off lights when the night comes
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: scene.turn_on
    entity_id:
      - scene.night
