- alias: Turn on indoor lights in early morning
  trigger:
    platform: time
    at: '06:00:00'
  condition:
    condition: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 2.0
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.everspring_ad146_in_wall_dimmer_module_level_5_0

- alias: Turn off indoor lights when sun is up
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 2.0
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.everspring_ad146_in_wall_dimmer_module_level_5_0

- alias: Turn on indoor lights when sun goes down
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 4.0
  condition:
    condition: time
    before: '22:30:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.everspring_ad146_in_wall_dimmer_module_level_5_0

- alias: Turn off lights in the evening
  trigger:
    platform: time
    at: '22:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.everspring_ad146_in_wall_dimmer_module_level_5_0
