- alias: Turn on indoor lights in early morning
  trigger:
    platform: time
    after: '06:00:00'
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.hall_level_5_0

- alias: Turn off indoor lights when sun is up
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    above: 4.0
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.hall_level_5_0

- alias: Turn on indoor lights when sun goes down
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 6.0
  action:
    service: homeassistant.turn_on
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.hall_level_5_0

- alias: Turn off lights in the evening
  trigger:
    platform: time
    after: '22:30:00'
  action:
    service: homeassistant.turn_off
    entity_id:
      - light.livingroom_window
      - light.livingroom_other
      - light.livingroom_corner
      - light.hall_level_5_0
