light:
  - platform: rfxtrx
    devices:
      0b11000d0085feb608010f70:
        name: attic_window

sensor:
  - platform: rfxtrx
    devices:
      0a5209024b0000d32f0179:
        name: attic_th03
        data_type:
          - Temperature
          - Humidity
      0a52093dc10000c8220279:
        name: attic_th04
        data_type:
          - Temperature
          - Humidity
  - platform: template
    sensors:
      attic_heating_cable_power:
        value_template: '{{ states("sensor.telldus_tzwp102_plugin_switch_power_2") }}'
        unit_of_measurement: 'W'
      attic_heating_cable_energy:
        value_template: '{{ states("sensor.telldus_tzwp102_plugin_switch_energy_2") }}'
        unit_of_measurement: 'kWh'
      attic_ventilation_power:
        value_template: '{{ states("sensor.telldus_tzwp102_plugin_switch_power") }}'
        unit_of_measurement: 'W'
      attic_ventilation_energy:
        value_template: '{{ states("sensor.telldus_tzwp102_plugin_switch_energy") }}'
        unit_of_measurement: 'kWh'

switch:
  - platform: template
    switches:
      attic_heating_cable:
        value_template: '{{ is_state("switch.telldus_tzwp102_plugin_switch_switch_2", "on") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.telldus_tzwp102_plugin_switch_switch_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.telldus_tzwp102_plugin_switch_switch_2
      attic_ventilation:
        value_template: '{{ is_state("switch.telldus_tzwp102_plugin_switch_switch", "on") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.telldus_tzwp102_plugin_switch_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.telldus_tzwp102_plugin_switch_switch

automation:
  - alias: Turn on attic lights when sun goes down
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 0.0
    action:
      service: homeassistant.turn_on
      data:
        entity_id:
          - light.attic_window
  - alias: Turn off attic lights when the sun goes up
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 0.0
    action:
      service: homeassistant.turn_off
      data:
        entity_id:
          - light.attic_window

group:
  attic:
    entities:
      - light.attic_window
      - sensor.attic_th03_temperature
      - sensor.attic_th03_humidity
      - sensor.attic_th04_temperature
      - sensor.attic_th04_humidity
      - switch.attic_heating_cable
      - sensor.attic_heating_cable_power
      - sensor.attic_heating_cable_energy
      - switch.attic_ventilation
      - sensor.attic_ventilation_power
      - sensor.attic_ventilation_energy

homeassistant:
  customize:
    group.attic_view:
      friendly_name: Vinden
    group.attic:
      friendly_name: Vinden
    sensor.attic_th03_temperature:
      friendly_name: Temperatur norrsidan
    sensor.attic_th03_humidity:
      friendly_name: Luftfuktighet norrsidan
    sensor.attic_th04_temperature:
      friendly_name: Temperatur sydsidan
    sensor.attic_th04_humidity:
      friendly_name: Luftfuktighet sydsidan
    light.attic_window:
      friendly_name: Fönsterlampan
    switch.attic_ventilation:
      friendly_name: Ventilation
    sensor.attic_ventilation_energy:
      friendly_name: Ventilation, energiåtgång
    sensor.attic_ventilation_power:
      friendly_name: Ventilation, effektuttag
    switch.attic_heating_cable:
      friendly_name: Värmekabel
    sensor.attic_heating_cable_energy:
      friendly_name: Värmekabel, energiåtgång
    sensor.attic_heating_cable_power:
      friendly_name: Värmekabel, effektuttag
