sensor:
  - platform: template
    sensors:
      garage1_door_ui:
        value_template: >-
          {% if is_state('binary_sensor.garage_g1_door', 'off') %}
            stängd
          {% elif is_state('binary_sensor.garage_g1_door', 'on') %}
            öppen
          {% else %}
            okänt
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.garage_g1_door', 'off') %}
            mdi:door-closed
          {% elif is_state('binary_sensor.garage_g1_door', 'on') %}
            mdi:door-open
          {% else %}
            mdi:dots-horizontal
          {% endif %}
      garage2_door_ui:
        value_template: >-
          {% if is_state('binary_sensor.garage_g2_door', 'off') %}
            stängd
          {% elif is_state('binary_sensor.garage_g2_door', 'on') %}
            öppen
          {% else %}
            okänt
          {% endif %}
        icon_template: >-
          {% if is_state('binary_sensor.garage_g2_door', 'off') %}
            mdi:door-closed
          {% elif is_state('binary_sensor.garage_g2_door', 'on') %}
            mdi:door-open
          {% else %}
            mdi:dots-horizontal
          {% endif %}

alert:
  garage1:
    name: garage1
    entity_id: binary_sensor.garage_g1_door
    state: 'on'
    repeat:
      - 10
      - 60
      - 120
      - 1440
    skip_first: true
    message: Garageporten till G1 är fortfarande öppen
    done_message: Garageporten till G1 har nu stängts
    notifiers:
      - family
  garage2:
    name: garage2
    entity_id: binary_sensor.garage_g2_door
    state: 'on'
    repeat:
      - 10
      - 60
      - 120
      - 1440
    skip_first: true
    message: Garageporten till G2 är fortfarande öppen
    done_message: Garageporten till G2 har nu stängts
    notifiers:
      - family

homeassistant:
  customize:
    sensor.garage1_door_ui:
      friendly_name: Garageport G1
    sensor.garage2_door_ui:
      friendly_name: Garageport G2
