# binary_sensor:
#   - platform: template
#     sensors:
#       guestroom_motion:
#         entity_id: sensor.fibaro_system_fgms001zw5_motion_sensor_burglar
#         value_template: '{{ is_state("sensor.fibaro_system_fgms001zw5_motion_sensor_burglar", "8") }}'
#         device_class: motion

sensor:
  - platform: template
    sensors:
      guestroom_status:
        value_template: >-
          {% if is_state("binary_sensor.guestroom_motion", "on") %}
            upptaget
          {% else %}
            ledigt
          {% endif %}
        icon_template: >-
          {% if is_state("binary_sensor.guestroom_motion", "on") %}
            mdi:close-circle
          {% else %}
            mdi:human-male-female
          {% endif %}
      # guestroom_luminance:
      #   value_template: "{{ states('sensor.fibaro_system_fgms001zw5_motion_sensor_luminance') }}"
      #   unit_of_measurement: 'lux'
      # guestroom_temperature:
      #   value_template: "{{ states('sensor.fibaro_system_fgms001zw5_motion_sensor_temperature') }}"
      #   unit_of_measurement: '°C'
      # guestroom_battery:
      #   value_template: "{{ state_attr('zwave.fibaro_system_fgms001zw5_motion_sensor', 'battery_level') }}"
      #   unit_of_measurement: '%'

group:
  guestroom:
    - light.guest_toilet
    - sensor.guestroom_status
    - sensor.guestroom_luminance
    - sensor.guestroom_temperature

homeassistant:
  customize:
    group.guestroom:
      friendly_name: Gästtoaletten
    light.guest_toilet:
      friendly_name: Belysning
    sensor.guestroom_status:
      friendly_name: Gästtoaletten
    sensor.guestroom_luminance:
      friendly_name: Ljusnivå
    sensor.guestroom_temperature:
      friendly_name: Temperatur
    sensor.guestroom_battery:
      friendly_name: Närvarosensor gästtoalett
