light:
  - platform: rfxtrx
    devices:
      0b11000d0085feb605010f70:
        name: outdoor_back_and_plugin
  - platform: template
    lights:
      outdoor_front:
        value_template: '{{ is_state("switch.everspring_an179_in_wall_onoff_module_switch", "on") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.everspring_an179_in_wall_onoff_module_switch
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.everspring_an179_in_wall_onoff_module_switch
      outdoor_driveway:
        value_template: '{{ is_state("switch.everspring_an179_in_wall_onoff_module_switch_2", "on") }}'
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.everspring_an179_in_wall_onoff_module_switch_2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.everspring_an179_in_wall_onoff_module_switch_2
  - platform: mqtt
    name: outdoor_ledstrip_default
    availability_topic: "outdoor_ledstrip/status"
    command_topic: "outdoor_ledstrip/light/switch"
    state_topic: "outdoor_ledstrip/light/status"
    rgb_state_topic: "outdoor_ledstrip/rgb/status"
    rgb_command_topic: "outdoor_ledstrip/rgb/set"
    white_value_command_topic: "outdoor_ledstrip/white/set"
    white_value_state_topic: "outdoor_ledstrip/white/status"
    effect_command_topic: "outdoor_ledstrip/effect/set"
    effect_state_topic: "outdoor_ledstrip/effect/status"
    effect_list:
      - none
      - rainbow
  - platform: mqtt
    name: outdoor_ledstrip
    schema: json
    retain: yes
    command_topic: "outdoor_ledstrip/light/set"
    state_topic: "outdoor_ledstrip/light"
    availability_topic: "outdoor_ledstrip/status"
    effect: yes
    effect_list:
      - none
      - rainbow
    rgb: yes
    white_value: yes

automation:
  - alias: Turn on outdoor lights when sun goes down
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      below: 0.0
    action:
      service: scene.turn_on
      data:
        entity_id:
          - scene.outdoor_lights_on
  - alias: Turn off outdoor lights when the sun goes up
    trigger:
      platform: numeric_state
      entity_id: sun.sun
      value_template: '{{ state.attributes.elevation }}'
      above: 0.0
    action:
      service: scene.turn_on
      data:
        entity_id:
          - scene.outdoor_lights_off


sensor:
  - platform: template
    sensors:
      outdoor_driveway_luminance:
        value_template: '{{ states("sensor.aeon_labs_zw074_multisensor_gen5_luminance_3") }}'
        unit_of_measurement: 'lux'
        device_class: illuminance
      outdoor_driveway_humidity:
        value_template: '{{ states("sensor.aeon_labs_zw074_multisensor_gen5_relative_humidity_3") }}'
        unit_of_measurement: '%'
        device_class: humidity
      outdoor_driveway_temperature:
        value_template: '{{ states("sensor.aeon_labs_zw074_multisensor_gen5_temperature_3") }}'
        unit_of_measurement: '°C'
        device_class: temperature
      outdoor_driveway_battery:
        value_template: '{{ states("sensor.aeon_labs_zw074_multisensor_gen5_battery_level_3") }}'
        unit_of_measurement: '%'
        device_class: battery

scene:
  - name: outdoor_lights_on
    entities:
      light.outdoor_driveway: on
      light.outdoor_front: on
      light.outdoor_back_and_plugin: on
      # Twinkly lights are a bit too much Christmas like.
      # light.twinkly_lights: on
      light.hue_white_lamp_1: on
      light.hue_white_lamp_2: on
      light.outdoor_ledstrip:
        state: on
        effect: rainbow
  - name: outdoor_lights_off
    entities:
      group.outdoor_lights: off

group:
  outdoor_lights:
    entities:
      - light.outdoor_driveway
      - light.outdoor_front
      - light.outdoor_back_and_plugin
      - light.hue_white_lamp_1
      - light.hue_white_lamp_2
      - light.outdoor_ledstrip
      - light.twinkly_lights
  outdoor_sensors:
    entities:
      - sensor.outdoor_driveway_luminance
      - sensor.outdoor_driveway_humidity
      - sensor.outdoor_driveway_temperature
      - sensor.outdoor_driveway_battery

homeassistant:
  customize:
    group.outdoor_lights:
      friendly_name: Utomhusbelysning
    light.outdoor_driveway:
      friendly_name: Belysning garageuppfart
    light.outdoor_front:
      friendly_name: Belysning framsidan
    light.outdoor_back_and_plugin:
      friendly_name: Belysning baksidan och plugin
    light.outdoor_ledstrip:
      friendly_name: LED-list vid entrén
    light.hue_white_lamp_1:
      friendly_name: Lampa utanför garage 1
    light.hue_white_lamp_2:
      friendly_name: Lampa utanför garage 2
    group.outdoor_sensors:
      friendly_name: Utomhussensorer
    sensor.outdoor_driveway_luminance:
      friendly_name: Ljusnivå
    sensor.outdoor_driveway_humidity:
      friendly_name: Luftfuktighet
    sensor.outdoor_driveway_temperature:
      friendly_name: Temperatur
    sensor.outdoor_driveway_battery:
      friendly_name: Batteri Multisensor uteförråd
    light.twinkly_lights:
      friendly_name: Julbelysning uteförråd
